from Exception import Exception

class MyException(Exception):
    def __init__(self, aMessage, aParent):
        super().__init__(aMessage, aParent)

    def delete(self):
        pass

